<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
	<RootNamespace>Wolf3D</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.13" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="OpenTK.Audio.OpenAL" Version="4.8.2" />
		<PackageReference Include="NukedOPL3Sharp" Version="1.2.1" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="ppy.SDL2-CS" Version="1.0.82" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Models\" />
	</ItemGroup>

	<PropertyGroup>
		<PfWolfPk3SourceDir>$(MSBuildProjectDirectory)\..\..\pfwolf-pk3\</PfWolfPk3SourceDir>
	</PropertyGroup>
	<ItemGroup>
		<PfWolfPk3SourceFiles Include="$(PfWolfPk3SourceDir)**\*.*" />
	</ItemGroup>

	<Target Name="BuildPfWolfPk3" BeforeTargets="Build" Inputs="@(PfWolfPk3SourceFiles)" Outputs="$(TargetDir)pfwolf.pk3">
		<ZipDirectory SourceDirectory="$(PfWolfPk3SourceDir)" DestinationFile="$(TargetDir)pfwolf.pk3" Overwrite="true" />
		<ItemGroup>
			<FileWrites Include="$(TargetDir)pfwolf.pk3" />
		</ItemGroup>
	</Target>
</Project>
