namespace Wolf3D.Mappers;

internal static class AudioMappings
{
    /// <summary>
    /// Sound asset name that aliases to various types (Digitized, AdLib, PC) of the same sound effect.
    /// </summary>
    public static Dictionary<string, (string Digitized, string AdLib, string PC)> SoundMappingKeys = new Dictionary<string, (string Digitized, string AdLib, string PC)>
    {
        { "hitwall", new ("", "ADHITWALL", "PCHITWALL") },
        { "selectwpn", new ("", "ADSELECTWPN", "PCSELECTWPN") },
        { "selectitem", new ("", "ADSELECTITEM", "PCSELECTITEM") },
        { "heartbeat", new ("", "ADHEARTBEAT", "PCHEARTBEAT") },
        { "movegun2", new ("", "ADMOVEGUN2", "PCMOVEGUN2") },
        { "movegun1", new ("", "ADMOVEGUN1", "PCMOVEGUN1") },
        { "noway", new ("", "ADNOWAY", "PCNOWAY") },
        { "nazihitplayer", new ("", "ADNAZIHITPLAYER", "PCNAZIHITPLAYER") },
        { "schabbsthrow", new ("", "ADSCHABBSTHROW", "PCSCHABBSTHROW") },
        { "playerdeath", new ("", "ADPLAYERDEATH", "PCPLAYERDEATH") },
        { "dogdeath", new ("DOGDEATHSND", "ADDOGDEATH", "PCDOGDEATH") },
        { "atkgatling", new ("ATKGATLINGSND", "ADATKGATLING", "PCATKGATLING") },
        { "getkey", new ("", "ADGETKEY", "PCGETKEY") },
        { "noitem", new ("", "ADNOITEM", "PCNOITEM") },
        { "walk1", new ("", "ADWALK1", "PCWALK1") },
        { "walk2", new ("", "ADWALK2", "PCWALK2") },
        { "takedamage", new ("TAKEDAMAGESND", "ADTAKEDAMAGE", "PCTAKEDAMAGE") },
        { "gameover", new ("", "ADGAMEOVER", "PCGAMEOVER") },
        { "opendoor", new ("OPENDOORSND", "ADOPENDOOR", "PCOPENDOOR") },
        { "closedoor", new ("CLOSEDOORSND", "ADCLOSEDOOR", "PCCLOSEDOOR") },
        { "donothing", new ("", "ADDONOTHING", "PCDONOTHING") },
        { "halt", new ("HALTSND", "ADHALT", "PCHALT") },
        { "deathscream2", new ("DEATHSCREAM2SND", "ADDEATHSCREAM2", "PCDEATHSCREAM2") },
        { "atkknife", new ("", "ADATKKNIFE", "PCATKKNIFE") },
        { "atkpistol", new ("ATKPISTOLSND", "ADATKPISTOL", "PCATKPISTOL") },
        { "deathscream3", new ("", "ADDEATHSCREAM3", "PCDEATHSCREAM3") },
        { "atkmachinegun", new ("ATKMACHINEGUNSND", "ADATKMACHINEGUN", "PCATKMACHINEGUN") },
        { "hitenemy", new ("", "ADHITENEMY", "PCHITENEMY") },
        { "shootdoor", new ("", "ADSHOOTDOOR", "PCSHOOTDOOR") },
        { "deathscream1", new ("DEATHSCREAM1SND", "ADDEATHSCREAM1", "PCDEATHSCREAM1") },
        { "getmachine", new ("", "ADGETMACHINE", "PCGETMACHINE") },
        { "getammo", new ("", "ADGETAMMO", "PCGETAMMO") },
        { "shoot", new ("", "ADSHOOT", "PCSHOOT") },
        { "health1", new ("", "ADHEALTH1", "PCHEALTH1") },
        { "health2", new ("", "ADHEALTH2", "PCHEALTH2") },
        { "bonus1", new ("", "ADBONUS1", "PCBONUS1") },
        { "bonus2", new ("", "ADBONUS2", "PCBONUS2") },
        { "bonus3", new ("", "ADBONUS3", "PCBONUS3") },
        { "getgatling", new ("", "ADGETGATLING", "PCGETGATLING") },
        { "escpressed", new ("", "ADESCPRESSED", "PCESCPRESSED") },
        { "leveldone", new ("LEVELDONESND", "ADLEVELDONE", "PCLEVELDONE") },
        { "dogbark", new ("DOGBARKSND", "ADDOGBARK", "PCDOGBARK") },
        { "endbonus1", new ("", "ADENDBONUS1", "PCENDBONUS1") },
        { "endbonus2", new ("", "ADENDBONUS2", "PCENDBONUS2") },
        { "bonus1up", new ("", "ADBONUS1UP", "PCBONUS1UP") },
        { "bonus4", new ("", "ADBONUS4", "PCBONUS4") },
        { "pushwall", new ("PUSHWALLSND", "ADPUSHWALL", "PCPUSHWALL") },
        { "nobonus", new ("", "ADNOBONUS", "PCNOBONUS") },
        { "percent100", new ("", "ADPERCENT100", "PCPERCENT100") },
        { "bossactive", new ("", "ADBOSSACTIVE", "PCBOSSACTIVE") },
        { "mutti", new ("MUTTISND", "ADMUTTI", "PCMUTTI") },
        { "schutzad", new ("SCHUTZADSND", "ADSCHUTZAD", "PCSCHUTZAD") },
        { "ahhhg", new ("AHHHGSND", "ADAHHHG", "PCAHHHG") },
        { "die", new ("DIESND", "ADDIE", "PCDIE") },
        { "eva", new ("EVASND", "ADEVA", "PCEVA") },
        { "gutentag", new ("GUTENTAGSND", "ADGUTENTAG", "PCGUTENTAG") },
        { "leben", new ("LEBENSND", "ADLEBEN", "PCLEBEN") },
        { "scheist", new ("SCHEISTSND", "ADSCHEIST", "PCSCHEIST") },
        { "nazifire", new ("NAZIFIRESND", "ADNAZIFIRE", "PCNAZIFIRE") },
        { "bossfire", new ("BOSSFIRESND", "ADBOSSFIRE", "PCBOSSFIRE") },
        { "ssfire", new ("SSFIRESND", "ADSSFIRE", "PCSSFIRE") },
        { "slurpie", new ("SLURPIESND", "ADSLURPIE", "PCSLURPIE") },
        { "tot_hund", new ("TOT_HUNDSND", "ADTOT_HUND", "PCTOT_HUND") },
        { "meingott", new ("MEINGOTTSND", "ADMEINGOTT", "PCMEINGOTT") },
        { "schabbsha", new ("SCHABBSHASND", "ADSCHABBSHA", "PCSCHABBSHA") },
        { "hitlerha", new ("HITLERHASND", "ADHITLERHA", "PCHITLERHA") },
        { "spion", new ("SPIONSND", "ADSPION", "PCSPION") },
        { "neinsovas", new ("NEINSOVASSND", "ADNEINSOVA", "PCNEINSOVA") },
        { "dogattack", new ("DOGATTACKSND", "ADDOGATTACK", "PCDOGATTACK") },
        { "flamethrower", new ("", "ADFLAMETHROWER", "PCFLAMETHROWER") },
        { "mechstep", new ("MECHSTEPSND", "ADMECHSTEP", "PCMECHSTEP") },
        { "goobs", new ("", "ADGOOBS", "PCGOOBS") },
        { "yeah", new ("YEAHSND", "ADYEAH", "PCYEAH") },
        { "deathscream4", new ("DEATHSCREAM4SND", "ADDEATHSCREAM4", "PCDEATHSCREAM4") },
        { "deathscream5", new ("DEATHSCREAM5SND", "ADDEATHSCREAM5", "PCDEATHSCREAM5") },
        { "deathscream6", new ("DEATHSCREAM6SND", "ADDEATHSCREAM6", "PCDEATHSCREAM6") },
        { "deathscream7", new ("DEATHSCREAM7SND", "ADDEATHSCREAM7", "PCDEATHSCREAM7") },
        { "deathscream8", new ("DEATHSCREAM8SND", "ADDEATHSCREAM8", "PCDEATHSCREAM8") },
        { "deathscream9", new ("DEATHSCREAM9SND", "ADDEATHSCREAM9", "PCDEATHSCREAM9") },
        { "donner", new ("DONNERSND", "ADDONNE", "PCDONNE") },
        { "eine", new ("EINESND", "ADEINE", "PCEINE") },
        { "erlauben", new ("ERLAUBENSND", "ADERLAUBEN", "PCERLAUBEN") },
        { "kein", new ("KEINSND", "ADKEIN", "PCKEIN") },
        { "mein", new ("MEINSND", "ADMEIN", "PCMEIN") },
        { "rose", new ("ROSESND", "ADROSE", "PCROSE") },
        { "missilefire", new ("", "ADMISSILEFIRE", "PCMISSILEFIRE") },
        { "missilehit", new ("", "ADMISSILEHIT", "PCMISSILEHIT") }
    };

    public static List<string> MusicKeys = new() {
        "Corner",
        "Dungeon",
        "MarchToWar",
        "GetThem",
        "PoundingHeadache",
        "HitlerWaltz",
        "KillTheSOB",
        "HorstWesselLied",
        "NaziAnthem",
        "PrisonerOfWar",
        "Salute",
        "Searching",
        "Suspense",
        "VictorsFuneral",
        "Wondering",
        "FunkYou",
        "EndLevel",
        "GoingAfterHitler",
        "Lurking",
        "Ultimate",
        "NaziRap",
        "ZeroHour",
        "TheTwelfthHour",
        "Roster",
        "YoureAHero",
        "VictoryMarch",
        "PacMan"
    };

    public static List<string> AudioTKeys => SoundMappingKeys.Values.Select(x => x.PC)
        .Concat(SoundMappingKeys.Values.Select(x => x.AdLib)
        .Concat(SoundMappingKeys.Values.Select(x => x.Digitized)))
        .Concat(MusicKeys).ToList();
    
}
