namespace Wolf3D.Mappers;

internal static class AudioMappings
{
    public static Dictionary<string, (string Digitized, string AdLib, string PC)> FallbackMapping = new Dictionary<string, (string Digitized, string AdLib, string PC)>
    {
        { "HITWALLSND", new ("", "ADHITWALL", "PCHITWALL") },
        { "SELECTWPNSND", new ("", "ADSELECTWPN", "PCSELECTWPN") },
        { "SELECTITEMSND", new ("", "ADSELECTITEM", "PCSELECTITEM") },
        { "HEARTBEATSND", new ("", "ADHEARTBEAT", "PCHEARTBEAT") },
        { "MOVEGUN2SND", new ("", "ADMOVEGUN2", "PCMOVEGUN2") },
        { "MOVEGUN1SND", new ("", "ADMOVEGUN1", "PCMOVEGUN1") },
        { "NOWAYSND", new ("", "ADNOWAY", "PCNOWAY") },
        { "NAZIHITPLAYERSND", new ("", "ADNAZIHITPLAYER", "PCNAZIHITPLAYER") },
        { "SCHABBSTHROWSND", new ("", "ADSCHABBSTHROW", "PCSCHABBSTHROW") },
        { "PLAYERDEATHSND", new ("", "ADPLAYERDEATH", "PCPLAYERDEATH") },
        { "DOGDEATHSND", new ("", "ADDOGDEATH", "PCDOGDEATH") },
        { "ATKGATLINGSND", new ("", "ADATKGATLING", "PCATKGATLING") },
        { "GETKEYSND", new ("", "ADGETKEY", "PCGETKEY") },
        { "NOITEMSND", new ("", "ADNOITEM", "PCNOITEM") },
        { "WALK1SND", new ("", "ADWALK1", "PCWALK1") },
        { "WALK2SND", new ("", "ADWALK2", "PCWALK2") },
        { "TAKEDAMAGESND", new ("", "ADTAKEDAMAGE", "PCTAKEDAMAGE") },
        { "GAMEOVERSND", new ("", "ADGAMEOVER", "PCGAMEOVER") },
        { "OPENDOORSND", new ("", "ADOPENDOOR", "PCOPENDOOR") },
        { "CLOSEDOORSND", new ("", "ADCLOSEDOOR", "PCCLOSEDOOR") },
        { "DONOTHINGSND", new ("", "ADDONOTHING", "PCDONOTHING") },
        { "HALTSND", new ("", "ADHALT", "PCHALT") },
        { "DEATHSCREAM2SND", new ("", "ADDEATHSCREAM2", "PCDEATHSCREAM2") },
        { "ATKKNIFESND", new ("", "ADATKKNIFE", "PCATKKNIFE") },
        { "ATKPISTOLSND", new ("", "ADATKPISTOL", "PCATKPISTOL") },
        { "DEATHSCREAM3SND", new ("", "ADDEATHSCREAM3", "PCDEATHSCREAM3") },
        { "ATKMACHINEGUNSND", new ("", "ADATKMACHINEGUN", "PCATKMACHINEGUN") },
        { "HITENEMYSND", new ("", "ADHITENEMY", "PCHITENEMY") },
        { "SHOOTDOORSND", new ("", "ADSHOOTDOOR", "PCSHOOTDOOR") },
        { "DEATHSCREAM1SND", new ("", "ADDEATHSCREAM1", "PCDEATHSCREAM1") },
        { "GETMACHINESND", new ("", "ADGETMACHINE", "PCGETMACHINE") },
        { "GETAMMOSND", new ("", "ADGETAMMO", "PCGETAMMO") },
        { "SHOOTSND", new ("", "ADSHOOT", "PCSHOOT") },
        { "HEALTH1SND", new ("", "ADHEALTH1", "PCHEALTH1") },
        { "HEALTH2SND", new ("", "ADHEALTH2", "PCHEALTH2") },
        { "BONUS1SND", new ("", "ADBONUS1", "PCBONUS1") },
        { "BONUS2SND", new ("", "ADBONUS2", "PCBONUS2") },
        { "BONUS3SND", new ("", "ADBONUS3", "PCBONUS3") },
        { "GETGATLINGSND", new ("", "ADGETGATLING", "PCGETGATLING") },
        { "ESCPRESSEDSND", new ("", "ADESCPRESSED", "PCESCPRESSED") },
        { "LEVELDONESND", new ("", "ADLEVELDONE", "PCLEVELDONE") },
        { "DOGBARKSND", new ("", "ADDOGBARK", "PCDOGBARK") },
        { "ENDBONUS1SND", new ("", "ADENDBONUS1", "PCENDBONUS1") },
        { "ENDBONUS2SND", new ("", "ADENDBONUS2", "PCENDBONUS2") },
        { "BONUS1UPSND", new ("", "ADBONUS1UP", "PCBONUS1UP") },
        { "BONUS4SND", new ("", "ADBONUS4", "PCBONUS4") },
        { "PUSHWALLSND", new ("", "ADPUSHWALL", "PCPUSHWALL") },
        { "NOBONUSSND", new ("", "ADNOBONUS", "PCNOBONUS") },
        { "PERCENT100SND", new ("", "ADPERCENT100", "PCPERCENT100") },
        { "BOSSACTIVESND", new ("", "ADBOSSACTIVE", "PCBOSSACTIVE") },
        { "MUTTISND", new ("", "ADMUTTI", "PCMUTTI") },
        { "SCHUTZADSND", new ("", "ADSCHUTZAD", "PCSCHUTZAD") },
        { "AHHHGSND", new ("", "ADAHHHG", "PCAHHHG") },
        { "DIESND", new ("", "ADDIE", "PCDIE") },
        { "EVASND", new ("", "ADEVA", "PCEVA") },
        { "GUTENTAGSND", new ("", "ADGUTENTAG", "PCGUTENTAG") },
        { "LEBENSND", new ("", "ADLEBEN", "PCLEBEN") },
        { "SCHEISTSND", new ("", "ADSCHEIST", "PCSCHEIST") },
        { "NAZIFIRESND", new ("", "ADNAZIFIRE", "PCNAZIFIRE") },
        { "BOSSFIRESND", new ("", "ADBOSSFIRE", "PCBOSSFIRE") },
        { "SSFIRESND", new ("", "ADSSFIRE", "PCSSFIRE") },
        { "SLURPIESND", new ("", "ADSLURPIE", "PCSLURPIE") },
        { "TOT_HUNDSND", new ("", "ADTOT_HUND", "PCTOT_HUND") },
        { "MEINGOTTSND", new ("", "ADMEINGOTT", "PCMEINGOTT") },
        { "SCHABBSHASND", new ("", "ADSCHABBSHA", "PCSCHABBSHA") },
        { "HITLERHASND", new ("", "ADHITLERHA", "PCHITLERHA") },
        { "SPIONSND", new ("", "ADSPION", "PCSPION") },
        { "NEINSOVASSND", new ("", "ADNEINSOVA", "PCNEINSOVA") },
        { "DOGATTACKSND", new ("", "ADDOGATTACK", "PCDOGATTACK") },
        { "FLAMETHROWERSND", new ("", "ADFLAMETHROWER", "PCFLAMETHROWER") },
        { "MECHSTEPSND", new ("", "ADMECHSTEP", "PCMECHSTEP") },
        { "GOOBSSND", new ("", "ADGOOBS", "PCGOOBS") },
        { "YEAHSND", new ("", "ADYEAH", "PCYEAH") },
        { "DEATHSCREAM4SND", new ("", "ADDEATHSCREAM4", "PCDEATHSCREAM4") },
        { "DEATHSCREAM5SND", new ("", "ADDEATHSCREAM5", "PCDEATHSCREAM5") },
        { "DEATHSCREAM6SND", new ("", "ADDEATHSCREAM6", "PCDEATHSCREAM6") },
        { "DEATHSCREAM7SND", new ("", "ADDEATHSCREAM7", "PCDEATHSCREAM7") },
        { "DEATHSCREAM8SND", new ("", "ADDEATHSCREAM8", "PCDEATHSCREAM8") },
        { "DEATHSCREAM9SND", new ("", "ADDEATHSCREAM9", "PCDEATHSCREAM9") },
        { "DONNERSND", new ("", "ADDONNE", "PCDONNE") },
        { "EINESND", new ("", "ADEINE", "PCEINE") },
        { "ERLAUBENSND", new ("", "ADERLAUBEN", "PCERLAUBEN") },
        { "KEINSND", new ("", "ADKEIN", "PCKEIN") },
        { "MEINSND", new ("", "ADMEIN", "PCMEIN") },
        { "ROSESND", new ("", "ADROSE", "PCROSE") },
        { "MISSILEFIRESND", new ("", "ADMISSILEFIRE", "PCMISSILEFIRE") },
        { "MISSILEHITSND", new ("", "ADMISSILEHIT", "PCMISSILEHIT") }
    };

    public static List<string> SoundKeys = new()
    {
        "HITWALLSND",
        "SELECTWPNSND",
        "SELECTITEMSND",
        "HEARTBEATSND",
        "MOVEGUN2SND",
        "MOVEGUN1SND",
        "NOWAYSND",
        "NAZIHITPLAYERSND",
        "SCHABBSTHROWSND",
        "PLAYERDEATHSND",
        "DOGDEATHSND",
        "ATKGATLINGSND",
        "GETKEYSND",
        "NOITEMSND",
        "WALK1SND",
        "WALK2SND",
        "TAKEDAMAGESND",
        "GAMEOVERSND",
        "OPENDOORSND",
        "CLOSEDOORSND",
        "DONOTHINGSND",
        "HALTSND",
        "DEATHSCREAM2SND",
        "ATKKNIFESND",
        "ATKPISTOLSND",
        "DEATHSCREAM3SND",
        "ATKMACHINEGUNSND",
        "HITENEMYSND",
        "SHOOTDOORSND",
        "DEATHSCREAM1SND",
        "GETMACHINESND",
        "GETAMMOSND",
        "SHOOTSND",
        "HEALTH1SND",
        "HEALTH2SND",
        "BONUS1SND",
        "BONUS2SND",
        "BONUS3SND",
        "GETGATLINGSND",
        "ESCPRESSEDSND",
        "LEVELDONESND",
        "DOGBARKSND",
        "ENDBONUS1SND",
        "ENDBONUS2SND",
        "BONUS1UPSND",
        "BONUS4SND",
        "PUSHWALLSND",
        "NOBONUSSND",
        "PERCENT100SND",
        "BOSSACTIVESND",
        "MUTTISND",
        "SCHUTZADSND",
        "AHHHGSND",
        "DIESND",
        "EVASND",
        "GUTENTAGSND",
        "LEBENSND",
        "SCHEISTSND",
        "NAZIFIRESND",
        "BOSSFIRESND",
        "SSFIRESND",
        "SLURPIESND",
        "TOT_HUNDSND",
        "MEINGOTTSND",
        "SCHABBSHASND",
        "HITLERHASND",
        "SPIONSND",
        "NEINSOVASSND",
        "DOGATTACKSND",
        "FLAMETHROWERSND",
        "MECHSTEPSND",
        "GOOBSSND",
        "YEAHSND",
        "DEATHSCREAM4SND",
        "DEATHSCREAM5SND",
        "DEATHSCREAM6SND",
        "DEATHSCREAM7SND",
        "DEATHSCREAM8SND",
        "DEATHSCREAM9SND",
        "DONNERSND",
        "EINESND",
        "ERLAUBENSND",
        "KEINSND",
        "MEINSND",
        "ROSESND",
        "MISSILEFIRESND",
        "MISSILEHITSND",
    };

    public static List<string> MusicKeys = new() {
        "Corner",
        "Dungeon",
        "MarchToWar",
        "GetThem",
        "PoundingHeadache",
        "HitlerWaltz",
        "KillTheSOB",
        "HorstWesselLied",
        "NaziAnthem",
        "PrisonerOfWar",
        "Salute",
        "Searching",
        "Suspense",
        "VictorsFuneral",
        "Wondering",
        "FunkYou",
        "EndLevel",
        "GoingAfterHitler",
        "Lurking",
        "Ultimate",
        "NaziRap",
        "ZeroHour",
        "TheTwelfthHour",
        "Roster",
        "YoureAHero",
        "VictoryMarch",
        "PacMan"
    };
}
