namespace Wolf3D.Mappers;

internal static class GraphicsMappings
{
    public static Dictionary<int, string> ArtExternMap = new Dictionary<int, string>
    {
        { 3, "H_BJ" },
        { 4, "H_Castle" },
        { 5, "KEYBOARD" },
        { 6, "JOYSTICK" },
        { 7, "HEALPIC" },
        { 8, "TREASPIC" },
        { 9, "GUNPIC" },
        { 10, "KEYPIC" },
        { 11, "H_Blaze" },
        { 12, "WEAPPIC" },
        { 13, "WOLFLOGO" },
        { 14, "IDLOGO" },
        { 15, "VISACARD" },
        { 16, "MASTCARD" },
        { 17, "H_TopWindow" },
        { 18, "H_LeftWindow" },
        { 19, "H_RightWindow" },
        { 20, "H_BottomInfo" },
        { 21, "SPEARAD" },
        { 22, "C_Options" },
        { 23, "C_Cursor1" },
        { 24, "C_Cursor2" },
        { 25, "C_NotSelected" },
        { 26, "C_Selected" },
        { 27, "C_FxTitle" },
        { 28, "C_DigiTitle" },
        { 29, "C_MusicTitle" },
        { 30, "C_MouseLBack" },
        { 31, "C_BabyMode" },
        { 32, "C_Easy" },
        { 33, "C_Normal" },
        { 34, "C_Hard" },
        { 35, "C_LoadSaveDisk" },
        { 36, "C_DiskLoading1" },
        { 37, "C_DiskLoading2" },
        { 38, "C_Control" },
        { 39, "C_Customize" },
        { 40, "C_LoadGame" },
        { 41, "C_SaveGame" },
        { 42, "C_Episode1" },
        { 43, "C_Episode2" },
        { 44, "C_Episode3" },
        { 45, "C_Episode4" },
        { 46, "C_Episode5" },
        { 47, "C_Episode6" },
        { 48, "C_Code" },
        { 49, "C_TimeCode" },
        { 50, "C_Level" },
        { 51, "C_Name" },
        { 52, "C_Score" },
        { 53, "C_Joy1" },
        { 54, "C_Joy2" },
        { 55, "L_Guy" },
        { 56, "FONTL058" },
        { 57, "FONTL048" },
        { 58, "FONTL049" },
        { 59, "FONTL050" },
        { 60, "FONTL051" },
        { 61, "FONTL052" },
        { 62, "FONTL053" },
        { 63, "FONTL054" },
        { 64, "FONTL055" },
        { 65, "FONTL056" },
        { 66, "FONTL057" },
        { 67, "FONTL037" },
        { 68, "FONTL065" },
        { 69, "FONTL066" },
        { 70, "FONTL067" },
        { 71, "FONTL068" },
        { 72, "FONTL069" },
        { 73, "FONTL070" },
        { 74, "FONTL071" },
        { 75, "FONTL072" },
        { 76, "FONTL073" },
        { 77, "FONTL074" },
        { 78, "FONTL075" },
        { 79, "FONTL076" },
        { 80, "FONTL077" },
        { 81, "FONTL078" },
        { 82, "FONTL079" },
        { 83, "FONTL080" },
        { 84, "FONTL081" },
        { 85, "FONTL082" },
        { 86, "FONTL083" },
        { 87, "FONTL084" },
        { 88, "FONTL085" },
        { 89, "FONTL086" },
        { 90, "FONTL087" },
        { 91, "FONTL088" },
        { 92, "FONTL089" },
        { 93, "FONTL090" },
        { 94, "FONTL033" },
        { 95, "FONTL039" },
        { 96, "L_GUY2" },
        { 97, "L_BJWINS" },
        { 98, "StatusBar" },
        { 99, "Title" },
        { 100, "PG13" },
        { 101, "CREDITS" },
        { 102, "HighScores" },
        { 103, "KNIFE" },
        { 104, "Gun" },
        { 105, "MachineGun" },
        { 106, "GatlingGun" },
        { 107, "NoKey" },
        { 108, "GoldKey" },
        { 109, "SilverKey" },
        { 110, "FONTN032" },
        { 111, "FONTN048" },
        { 112, "FONTN049" },
        { 113, "FONTN050" },
        { 114, "FONTN051" },
        { 115, "FONTN052" },
        { 116, "FONTN053" },
        { 117, "FONTN054" },
        { 118, "FONTN055" },
        { 119, "FONTN056" },
        { 120, "FONTN057" },
        { 121, "Face1A" },
        { 122, "Face1B" },
        { 123, "Face1C" },
        { 124, "Face2A" },
        { 125, "Face2B" },
        { 126, "Face2C" },
        { 127, "Face3A" },
        { 128, "Face3B" },
        { 129, "Face3C" },
        { 130, "Face4A" },
        { 131, "Face4B" },
        { 132, "Face4C" },
        { 133, "Face5A" },
        { 134, "Face5B" },
        { 135, "Face5C" },
        { 136, "Face6A" },
        { 137, "Face6B" },
        { 138, "Face6C" },
        { 139, "Face7A" },
        { 140, "Face7B" },
        { 141, "Face7C" },
        { 142, "Face8A" },
        { 143, "GotGatling" },
        { 144, "MutantBJ" },
        { 145, "Paused" },
        { 146, "GetPsyched" }
    };

    public static List<string> GraphicKeys =
    [
        "STRUCTPIC",
        "SmallFont",
        "LargeFont",
        "H_BJ",
        "H_Castle",
        "H_Blaze",
        "H_TopWindow",
        "H_LeftWindow",
        "H_RightWindow",
        "H_BottomInfo",
        "C_Options",
        "C_Cursor1",
        "C_Cursor2",
        "C_NotSelected",
        "C_Selected",
        "C_FxTitle",
        "C_DigiTitle",
        "C_MusicTitle",
        "C_MouseLBack",
        "C_BabyMode",
        "C_Easy",
        "C_Normal",
        "C_Hard",
        "C_LoadSaveDisk",
        "C_DiskLoading1",
        "C_DiskLoading2",
        "C_Control",
        "C_Customize",
        "C_LoadGame",
        "C_SaveGame",
        "C_Episode1",
        "C_Episode2",
        "C_Episode3",
        "C_Episode4",
        "C_Episode5",
        "C_Episode6",
        "C_Code",
        "C_TimeCode",
        "C_Level",
        "C_Name",
        "C_Score",
        "C_Joy1",
        "C_Joy2",
        "L_Guy",
        "FONTL058",
        "FONTL048",
        "FONTL049",
        "FONTL050",
        "FONTL051",
        "FONTL052",
        "FONTL053",
        "FONTL054",
        "FONTL055",
        "FONTL056",
        "FONTL057",
        "FONTL037",
        "FONTL065",
        "FONTL066",
        "FONTL067",
        "FONTL068",
        "FONTL069",
        "FONTL070",
        "FONTL071",
        "FONTL072",
        "FONTL073",
        "FONTL074",
        "FONTL075",
        "FONTL076",
        "FONTL077",
        "FONTL078",
        "FONTL079",
        "FONTL080",
        "FONTL081",
        "FONTL082",
        "FONTL083",
        "FONTL084",
        "FONTL085",
        "FONTL086",
        "FONTL087",
        "FONTL088",
        "FONTL089",
        "FONTL090",
        "FONTL033",
        "FONTL039",
        "L_GUY2",
        "L_BJWINS",
        "StatusBar",
        "Title",
        "PG13",
        "Credits",
        "HighScores",
        "Knife",
        "Gun",
        "MachineGun",
        "GatlingGun",
        "NoKey",
        "GoldKey",
        "SilverKey",
        "FONTN032",
        "FONTN048",
        "FONTN049",
        "FONTN050",
        "FONTN051",
        "FONTN052",
        "FONTN053",
        "FONTN054",
        "FONTN055",
        "FONTN056",
        "FONTN057",
        "Face1A",
        "Face1B",
        "Face1C",
        "Face2A",
        "Face2B",
        "Face2C",
        "Face3A",
        "Face3B",
        "Face3C",
        "Face4A",
        "Face4B",
        "Face4C",
        "Face5A",
        "Face5B",
        "Face5C",
        "Face6A",
        "Face6B",
        "Face6C",
        "Face7A",
        "Face7B",
        "Face7C",
        "Face8A",
        "GotGatling",
        "MutantBJ",
        "Paused",
        "GetPsyched",
        "Tile8",
        "OrderScreen",
        "ErrorScreen",
        "HelpArt",
        "Demo0",
        "Demo1",
        "Demo2",
        "Demo3",
        "EndArt1",
        "EndArt2",
        "EndArt3",
        "EndArt4",
        "EndArt5",
        "EndArt6",
    ];
}
